### ISSUE TITLE
ReferenceError: Can't find variable: Highcharts

### ISSUE THREAD

**Issue by RobertRajcool** [highcharts/highcharts-export-server#46]
ReferenceError: Can't find variable: Highcharts
TRACE:
 -> phantomjs://webpage.evaluate(): 63 (in function "createChart")
 -> phantomjs://webpage.evaluate(): 149
 -> phantomjs://webpage.evaluate(): 149
Exited with message 'ERROR: ReferenceError: Can't find variable: Highcharts'

**Comment by larsac07** [comment]
Hi, RobertRajcool.

It looks like you posted an error message. It states that the variable Highcharts is not defined. Without any more information from you, my best guess is that you did not include highcharts.js from http://code.highcharts.com/highcharts.js. Please refer to the guide at http://www.highcharts.com/docs/export-module/setting-up-the-server under "LEGACY EXPORT SERVERS" to set up your server correctly.

It is also my strong recommendation that you look at the new [Node.js export server](node-export-server), since the Java+Phantom/PHP+Batik-solutions are now considered legacy, and will not be updated with new features.

**Comment by larsac07** [comment]
Closing this for now, as there was no response from O.P.
